from selenium.webdriver.common.by import By

class LocatorsLoginPage():
    
    txt_email_xpath=(By.XPATH,"//input[@type='text']")
    txt_password_xpath=(By.XPATH,"//input[@type='password']")
    btn_login1_xpath=(By.XPATH,"//button[@type='submit']")
    text_Dashboard=(By.XPATH,"//h2[.=' Dashboard ']")

class LocatorsDashboardPage():
    # ddbtn_lang_xpath="//div[@class='d-flex justify-content-between align-items-center lang_custom_drpdown']"
    German_assertion_x=(By.XPATH,"//div[@class='row']/div[2]//p[.='Übersicht Abteilungen'][@class='mb-0']")
    ddbtn_lang_xpath=(By.XPATH,"//img[@class='ml-1 downIcon']")
    dd_engLang_xpath= (By.XPATH, "//div[contains(text(),'EN')]")
    link_project_xpath= (By.XPATH, "//p[normalize-space()='Projects']")
    pic_profile_xpath= (By.XPATH,"//div[@class='profile_thumbnail']")
    txt_prof_xpat= (By.XPATH,"//div[@class='md-list-item-content md-ripple']//span[contains(text(),'Profile')]")
    # notification_img_x= (By.XPATH,"//div[@class='notifications']//button[@type='button']//div[@class='md-badge-content']/img")
    notification_img_x= (By.XPATH,"/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/div[1]/div[1]/img[1]")
    label_ntfnAssert_x= (By.XPATH,"//div[@class='notification_txt title_20']")
    # label_ntfnAssert_x= (By.XPATH,"/html[1]/body[1]/div[3]/div[1]/ul[1]/div[1]/div[1]/div[1]")
    label_markasread_assert= (By.XPATH,"//ul[@class='md-list md-theme-default']//div[@class='mark_all_read font_16 font-weight-600 cursor-pointer'][contains(text(),'Mark all as read')]")
    label_viewAllNtfn_assert= (By.XPATH,"//ul[@class='md-list md-theme-default']//div[@class='font_16 text-primary py-20 font-weight-600 cursor-pointer'][contains(text(),'View all Notifications')]")
    # label_viewAllNtfn_assert= (By.XPATH,"/html[1]/body[1]/div[2]/div[1]/ul[1]/div[4]/a[1]/div[1]")
    scroll_ntfnScreen_x= (By.XPATH,"//p[contains(text(),'There is a meeting assigned to you on 2023-07-25 f')]")
    img_menuIcon_x= (By.XPATH,"//div[@class='d-flex align-items-center']/a/img[@class='hamburger_icon']")
    txt_footer_version=(By.XPATH,"//div[@class='copy_wright_text']/p[contains(@class,'desktop_view')][@class='desktop_view']")
    txt_footer_co_name=(By.XPATH,"//div[@class='footer_wrapper']/p[.='Developed by Bix Bytes Solutions AG']")
    link_dashboard_x=(By.XPATH,"//ul[@class='inner_content scroll_bar']/li//p[.='Dashboard']")

    label_H_Kanban_x= (By.XPATH,"//p[@class='mb-0'][normalize-space()='Kanban']")
    kanban_subFeature_x= (By.XPATH,"//div[@class='bpmt_card kanban_wrapper']//h2")
    label_qualify_x=(By.XPATH,"//h2[normalize-space()='Qualify']")
    label_Analyze_x=(By.XPATH,"//h2[normalize-space()='Analyze']")
    label_Offer_x=(By.XPATH,"/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/h2[1]")
    dd_kanbanAnalyse_x=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/*[name()='svg'][1]/*[name()='path'][1]")
    btn_kanbanAnalyze_close=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]")
    # btn_cancel_diaB_kanAna_x=(By.XPATH, "//footer[@id='confirm-modal___BV_modal_footer_']/button[2]//div[@class='md-button-content']")
    btn_cancel_diaB_kanAna_x=(By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/footer[1]/button[2]/div[1]/div[1]")
    label_Negotiate_x=(By.XPATH,"//h2[.='Negotiate']")
    img_fullview_x=(By.XPATH,"//a[@href='/pmtool/kanban']//div[@class='expand-view']//img[@alt='date']")
    label_fullview_x=(By.XPATH,"//a[@href='/pmtool/kanban']//div[@class='expand-view']//p[@class='mb-0 pr-10'][normalize-space()='Full view']")
    

    label_deptOverview_x=(By.XPATH,"//p[.='Department Overview']")
    # dd_datearrow_x=(By.XPATH,"//div[contains(@class,'md-field')]//input[@id='md-input-yfjxyjem6'][@class='md-input md-input md-select-value']")
    # dd_datearrow_x=(By.XPATH,"//div[@class='md-menu md-select lineHeight20']")
    dd_datearrow_x=(By.XPATH,"/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]")
    # Date_dd_x=(By.XPATH,"//ul[@class='md-list md-theme-default']/li//span")
    dd_3elements=(By.XPATH,"//div[@class='md-menu-content-container md-scrollbar md-theme-default']//ul//li")
    label_deptMonth_x=(By.XPATH,"//ul[@class='md-list md-theme-default']//span[@class='md-list-item-text'][.='Month']")
    label_deptWeek_x=(By.XPATH,"//ul[@class='md-list md-theme-default']//span[@class='md-list-item-text'][.='Week']")
    label_deptDay_x=(By.XPATH,"//ul[@class='md-list md-theme-default']//span[@class='md-list-item-text'][.='Day']")
    Actual_meet_RD=(By.XPATH,"//div[@class='apexcharts-legend-series']/span[@class='apexcharts-legend-text']")
    three_buttons_Dept4Ele=(By.XPATH,"//div[contains(@class,'apexcharts-legend')]")
    three_buttons_Dept3Ele=(By.XPATH,"//div[@class='apexcharts-legend-series']/span[.='']")
    label_deptActual_x=(By.XPATH,"//span[.='Actual']")
    label_deptmeetings_x=(By.XPATH,"//span[.='Meetings']")
    label_RD_x=(By.XPATH,"//span[.='R&D']")


    label_H_Calender_x=(By.XPATH,"//p[@class='mb-0'][.='Calendar']")
    img_Calfullview_x=(By.XPATH,"//a[@href='/pmtool/calendar']//div[@class='expand-view']//img[@alt='date']")
    img_reverseArrow_x=(By.XPATH,"//img[@class='reverse-arrow']")
    img_forwardArrow_x=(By.XPATH,"//div[@class='d-flex mouse-over-change']//div[2]//img[1]")
    all_labels_of_calender_x=(By.XPATH,"//div[@class='mr-20']")
    label_calls_x=(By.XPATH,"//div[contains(text(),'Calls')]")
    label_Meetings_x=(By.XPATH,"//div[@class='mr-20'][.='Meetings']")
    label_todo_x=(By.XPATH,"(//div[@class='mr-20'])[3]")
    label_MilesstartDate_x=(By.XPATH,"//div[contains(text(),'Milestones: Start Date')]")
    label_MilesendDate_x=(By.XPATH,"//div[@class='d-flex align-items-center justify-content-between']//div[@class='mr-20'][normalize-space()='End Date']")
    label_sprintStDate_x=(By.XPATH,"//div[contains(text(),'Sprint: Start Date')]")
    label_sprintEndDt_x=(By.XPATH,"//div[@class='d-flex align-items-center justify-content-between flex-nowrap']//div[@class='mr-20'][normalize-space()='End Date']")

    dnd_qualify_kanban_drag=(By.XPATH, "(//h2[@class='kanban_header'])[1]/following-sibling::div[@class='block_wrapper noselect']/div[2]")
    # dnd_qualify_kanban_drag=(By.XPATH, "//p[normalize-space()='on hold. Warte auf Feedback']")
    dnd_analyze_drop=(By.XPATH, "(//div[@class='col ew-mn-260']/h2[@class='kanban_header'])[2]/following-sibling::div")
    # dnd_analyze_drop=(By.XPATH,"body > div:nth-child(2) > div:nth-child(1) > main:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2)")
    dnd_offer_drop=(By.XPATH, "(//h2[@class='kanban_header'])[3]/following-sibling::div")
    dnd_negotiate_drop=(By.XPATH, "(//h2[@class='kanban_header'])[4]/following-sibling::div")
    right_scrolling=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/p[2]")

class LocatorsProjectPage():
    # project_table_headings=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/table[1]/thead[1]/tr[1]/th/div[contains(.,'')]")
    # project_table_headings=(By.XPATH,"//table[@class='table table_header mb-0 cloned_table_fx_head']//tr//th")
    project_table_headings=(By.XPATH,"//table[@class='table table_header mb-0 cloned_table_fx_head']")
    assert_headline_project=(By.XPATH,"//h2[@class='navbar_title text-ellipsis ew-mx-450']")
    search_bar=(By.XPATH,"/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]")

    btn_3dots_xpath=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/table[2]/tbody[1]/tr[1]/td[14]/div[1]/div[1]/button[1]/div[1]/div[1]")
    # btn_3dots_xpath=(By.XPATH, "(//table/tbody/tr/td)[14]")
    contents_3dots_xpath=(By.XPATH, "//div[@class='md-menu-content-container md-scrollbar md-theme-default']/ul/li/descendant::span[@class='filter_text']")

    btn_next_x=(By.XPATH, "//button[.='Next']")
    after_click_next=(By.XPATH, "/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/ul[1]/li/button[@aria-checked='true']")
    btn_back_x=(By.XPATH,"//button[.='Back']")
    after_click_back=(By.XPATH, "//div[@class='main-content']//div[2]//div[2]//div[2]//ul[1]//li//button[@aria-checked='false']")
    btn_back_arrow=(By.XPATH,"(//div[@class='col-auto ml-auto']//button[@class='page-link'])[1]")
    btn_forward_arrow=(By.XPATH,"//button[@aria-label='Go to last page']")
    # dd_pages=(By.XPATH,"//div[@class='row no-gutters mt-25 mb-10 align-items-center']//input[@id='md-input-yuojo7k2']")
    dd_pages=(By.XPATH,"/html[1]/body[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/input[1]")
    # dd_pages_4ele=(By.XPATH,"//div[@class='md-menu-content-container md-scrollbar md-theme-default']/ul/li/button")
    dd_pages_4ele=(By.XPATH,"//ul[@class='md-list md-theme-default']/li")


    btn_3dots_milestone=(By.XPATH,"//div[@class='md-menu-content-container md-scrollbar md-theme-default']/ul/li/descendant::span[@class='filter_text'][.='Add Milestone']")
    btn_milestone_close_x=(By.XPATH, "//header[@id='add-milestone___BV_modal_header_']//img[@class='mr-1']")
    txt_assert_milestone_H=(By.XPATH, "//h2[normalize-space()='Milestone']")
    dd_milestone_x=(By.XPATH,"//input[@id='md-input-m2mqldvp'][@class='md-input md-input md-select-value']")
    dd_4Items_milestone_y=(By.XPATH,"//div[contains(@class,'md-menu-content-container')]/ul/li/button")

    btn_3dots_addSprint=(By.XPATH,"//div[@class='md-menu-content-container md-scrollbar md-theme-default']/ul/li/descendant::span[@class='filter_text'][.='Add Sprint']")
    assert_sprint_headline=(By.XPATH, "//h2[@class='title_32']")
    txtfield_sprintname_x=(By.XPATH, "//div[contains(@class,'md-field')]/label[.='Sprint Name']/following-sibling::input")
    assert_empty_sprint_errMsg=(By.XPATH, "//span[@class='md-error']")
    assert_BV_sprint_errMsg=(By.XPATH,"//span[@class='md-error']")
    assert_repeatSprint_errMsg=(By.XPATH,"//span[@class='flex-grow-1 text-center']")
    assert_sprint_startdate=(By.XPATH, "//div[@class='add-milestone-title'][.='Start Date']")
    assert_sprint_enddate=(By.XPATH, "//div[@class='add-milestone-title'][.='End Date']")
    txtfield_description_x=(By.XPATH,"/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]")
    dd_arrow_sprint=(By.XPATH,"//input[@class='md-input md-input md-select-value'][@name='milestoneId']")
    dd_sprint_4ele_x=(By.XPATH,"//div[contains(@class,'md-select-menu md-menu-content-bottom-start md-menu-content-small md-menu-content md-theme-default')]//li//button[1]//div[1]")
    btn_addSprint_add=(By.XPATH,"//footer[@class='modal-footer']/button[1]//div[@class='md-button-content']")


    btn_3dots_delete=(By.XPATH, "//div[contains(@class,'md-menu-content-container')]/ul/li//button[@class='md-button md-theme-default']/descendant::span[.='Delete']")
    btn_3dots_del_cancel=(By.XPATH, "//div[@id='delete-modal___BV_modal_content_']/footer/button[2]//div[@class='md-button-content']")
    btn_3dots_del_delete=(By.XPATH, "(//div[@id='delete-modal___BV_modal_content_']/footer/button/div/div[@class='md-button-content'])[1]")

    btn_addProject_x=(By.XPATH, "//button[@class='md-button md-primary btn_transparent md-theme-default']//div[@class='md-button-content']")
    txt_projName_x=(By.XPATH, "//div[@id='kanban-add-project___BV_modal_body_']/descendant::label[.='Project Name']/following-sibling::input[@type='text']")
    txt_startDate_x=(By.XPATH, "//div[@class='col-xl-6 col-6']//label[.='Start Date']/following-sibling::input[@class='md-input']")
    txt_endDate_x=(By.XPATH, "//label[.='End Date']/following-sibling::input[@class='md-input']")
    rbtn_internal_x=(By.XPATH, "//body/div[@id='kanban-add-project___BV_modal_outer_']/div[@id='kanban-add-project']/div[@class='modal-dialog modal-md modal-dialog-centered']/div[@id='kanban-add-project___BV_modal_content_']/div[@id='kanban-add-project___BV_modal_body_']/div[@class='create-project-spacing p-0']/form/div[@class='row']/div[@class='col-xl-6 col-12 order-xl-12 order-1']/div[1]/div[1]/div[2]/div[1]")
    rbtn_onEffort_x=(By.XPATH, "(//div[contains(@class,'md-radio')])[8]")
    dd_customers_x=(By.XPATH, "//div[@id='customerSelect']//div[@class='multiselect__tags']")
    dd_sel_customer=(By.XPATH, "//body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[124]/span")
    dd_project_lead=(By.XPATH, "//div[@id='projectleadSelect']//div[@class='multiselect__tags']")
    dd_sel_akash=(By.XPATH, "//div[@class='multiselect multiselect--active multiselect--above']//span[contains(text(),'Akash S')]")
    dd_account_manager=(By.XPATH, "//div[@id='accountManagerSelect']//div[@class='multiselect__tags']")
    dd_sel_adithi=(By.XPATH, "//div[@class='multiselect multiselect--active multiselect--above']//span[contains(text(),'Adithi Prabhu')]")
   
    
    # txt_proj_summary = (By.XPATH, "//label[normalize-space()='Project Summary']/following-sibling::textarea[@id='md-textarea-kz3igorzc'][@class='md-textarea']")
    txt_proj_summary = (By.XPATH, "//label[normalize-space()='Project Summary']/following-sibling::textarea")
    btn_submit_cre_proj=(By.XPATH, "//div[contains(text(),'Submit')]")
    btn_cancel_cre_proj=(By.XPATH, "//div[contains(text(),'Cancel')]")
    btn_close_cre_proj=(By.XPATH, "//button[@class='btn btn_close no-outline project_btn_close']//img[@class='mr-1']")
    assert_empty_proj_name=(By.XPATH, "//span[@class='md-error']")
    assert_empty_cust_errmsg=(By.XPATH, "//span[normalize-space()='Customer is required']")
    assert_empty_projlead_errmsg=(By.XPATH, "//span[normalize-space()='Project Lead is required']")
    cr_proj_contack=(By.XPATH, "//div[@id='commissionerSelect']//div[@class='multiselect__tags']")
    assert_empty_contact_list_msg=(By.XPATH, "//div[@class='multiselect multiselect--active']//span[@class='multiselect__option'][normalize-space()='List is empty.']")
    assert_proj_cr_success_msg=(By.XPATH,"//div[@class='md-snackbar border-round-10 md-position-center md-theme-default snakBar_success']")
    assert_proj_del_success_msg=(By.XPATH,"//div[@class='md-snackbar border-round-10 md-position-center md-theme-default snakBar_success']")
    asser_projectlead_with_projemp_text=(By.XPATH, "//div[@class='multiselect multiselect--active']//span[contains(text(),'Anand Rao')]")
    assert_projemp_with_projectlead_text=(By.XPATH, "//span[@class='multiselect__tag']//span[contains(text(),'Anand Rao')]")

    # btn_addCustomer_x=(By.XPATH, "//button[contains(@class,'md-button')]//div[contains(text(),'Add Customer')][@class='md-button-content']")
    btn_addCustomer_x=(By.XPATH, "/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[2]/button[1]")
    cust_company=(By.XPATH, "//label[.='Company']/following-sibling::input[@class='md-input']")
    cust_street=(By.XPATH, "//label[.='Street']/following-sibling::input[@class='md-input']")
    cust_streetNum=(By.XPATH, "//label[.='Street No.']/following-sibling::input[@class='md-input']")
    cust_zipcode=(By.XPATH, "//label[.='ZIP']/following-sibling::input[@class='md-input']")
    cust_city=(By.XPATH, "//label[.='City']/following-sibling::input[@class='md-input']")
    cust_country=(By.XPATH, "//div[@class='md-field underline_none multiselect-mdfield mb-5 md-theme-default']/label[.='Country']/..//div[@class='multiselect__select']")
    # cust_country=(By.XPATH, "//input[@placeholder='Country']")
    # cust_selFrance=(By.XPATH, "/html[1]/body[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[4]/span[1]/span[1]")
    cust_selFrance=(By.CSS_SELECTOR,"div[class='multiselect multiselect--above'] div[class='multiselect__tags']")
    cust_officePhone=(By.XPATH, "//label[.='Office phone']/following-sibling::input[@class='md-input']")
    cust_sel_industry=(By.XPATH, "//div[@class='md-field underline_none multiselect-mdfield mb-5 md-theme-default']/label[.='Industry']/..//div[@class='multiselect__select']")
    # cust_sel_healthcare=(By.XPATH, "//span[contains(text(),'Healthcare')]")
    cust_sel_industry_allEle=(By.XPATH, "(//div[contains(@class,'md-field')]/div)[15]//ul/li/span/span")
    cust_website_address=(By.XPATH, "//input[@id='homepageUrl']") 
    cust_technologies=(By.XPATH, "//input[@id='technologies'][@class='md-input']")   
    cust_dd_rspnsblty=(By.XPATH, "//div[@class='multiselect multiselect--above']//div[@class='multiselect__tags']")
    cust_respon_akshata=(By.XPATH, "(//div[@class='multiselect__tags'])[8]/following-sibling::div/ul/li/span/span[.='Akshatha K']")
    cust_sk_email=(By.XPATH, "//input[@id='email'][@class='md-input']")
    cust_dd_arrow_whrFund=(By.XPATH, "//div[@id='wherefoundSelect']//div[@class='multiselect__tags']")
    cust_sel_linkedIn=(By.XPATH, "//span[contains(text(),'LinkedIn')]")
    cust_txtField_details=(By.XPATH, "//textarea[@id='details'][@class='md-textarea']")
    cust_add_btn=(By.XPATH, "//body[1]/div[3]/div[1]/div[1]/div[1]/footer[1]/button[1]/div[1]")
    cust_cancel_btn=(By.XPATH, "//footer[@id='add-customer___BV_modal_footer_']//div[@class='md-button-content'][normalize-space()='Cancel']")
    cust_pageClsoe_btn=(By.XPATH, "//header[@id='add-customer___BV_modal_header_']//img[@class='mr-1']")

    add_contact_btn=(By.XPATH, "//div[contains(text(),'Add Contact')]")
    add_con_login_btn=(By.XPATH, "//body[1]/div[3]/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]")
    add_con_inactive_btn=(By.XPATH, "//body[1]/div[3]/div[1]/div[1]/div[1]/header[1]/div[2]/div[1]/div[1]/div[1]/div[1]")
    add_con_close_btn=(By.XPATH, "//header[@id='add-contact___BV_modal_header_']//img[@class='mr-1']")
    add_con_fname=(By.XPATH, "//input[@id='first-name'][@class='md-input']")
    add_con_lname=(By.XPATH,"//input[@id='md-input-vsfcr9d'][@class='md-input']")
    add_con_jobrole=(By.XPATH,"//input[@id='job'][@class='md-input']")
    add_con_telephone=(By.XPATH,"//input[@id='md-input-fosnr85md']")
    add_con_mobile=(By.XPATH,"//input[@id='md-input-3ioqd1arq'][@class='md-input']")
    add_con_email=(By.XPATH,"//input[@id='emailId'][@class='md-input']")
    add_con_DOB=(By.XPATH,"//input[@id='dateOfBirth'][@class='md-input']")
    add_con_interest=(By.XPATH,"//input[@id='interests'][@class='md-input']")
    add_con_updates=(By.XPATH,"//input[@id='update'][@class='md-input']")
    add_con_btnAdd=(By.XPATH,"//body[1]/div[3]/div[1]/div[1]/div[1]/footer[1]/button[1]/div[1]")
    add_con_btncancel=(By.XPATH,"//body[1]/div[3]/div[1]/div[1]/div[1]/footer[1]/button[2]/div[1]")


                       
